2023-06-12 14:58:01,598 INFO server.py:59: 
2023-06-12 14:58:01,604 ERROR base_events.py:1771: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<handle_conn() done, defined at /Users/ljh/Documents/asyncio/src/server/server.py:11> exception=TypeError("'StreamWriter' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "/Users/ljh/Documents/asyncio/src/server/server.py", line 16, in handle_conn
    while True:
TypeError: 'StreamWriter' object does not support the asynchronous context manager protocol
2023-06-12 14:58:01,606 ERROR base_events.py:1771: Task exception was never retrieved
future: <Task finished name='Task-6' coro=<handle_conn() done, defined at /Users/ljh/Documents/asyncio/src/server/server.py:11> exception=TypeError("'StreamWriter' object does not support the asynchronous context manager protocol")>
Traceback (most recent call last):
  File "/Users/ljh/Documents/asyncio/src/server/server.py", line 16, in handle_conn
    while True:
TypeError: 'StreamWriter' object does not support the asynchronous context manager protocol
2023-06-12 14:58:02,634 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:02,638 INFO server.py:42: serving on ('::', 8888, 0, 0), ('0.0.0.0', 8888)
2023-06-12 14:58:04,046 INFO server.py:57: 
2023-06-12 14:58:04,950 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:04,953 INFO server.py:42: serving on ('::', 8888, 0, 0), ('0.0.0.0', 8888)
2023-06-12 14:58:05,830 INFO server.py:57: 
2023-06-12 14:58:08,102 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:08,105 INFO server.py:42: serving on ('0.0.0.0', 8888), ('::', 8888, 0, 0)
2023-06-12 14:58:09,278 INFO server.py:57: 
2023-06-12 14:58:11,086 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:11,087 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:11,087 INFO client.py:53: [Errno 61] Connect call failed ('192.168.1.31', 8888)
2023-06-12 14:58:12,293 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:12,294 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:12,295 INFO client.py:53: [Errno 61] Connect call failed ('192.168.1.31', 8888)
2023-06-12 14:58:13,037 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:13,038 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:13,039 INFO client.py:53: [Errno 61] Connect call failed ('192.168.1.31', 8888)
2023-06-12 14:58:15,280 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:15,284 INFO server.py:42: serving on ('::', 8888, 0, 0), ('0.0.0.0', 8888)
2023-06-12 14:58:17,480 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:17,480 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:17,481 INFO server.py:14: accepting connection from ('192.168.1.31', 51630)
2023-06-12 14:58:18,586 INFO client.py:53: 
2023-06-12 14:58:18,601 INFO server.py:31: Connection lost
2023-06-12 14:58:20,127 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:20,128 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:20,129 INFO server.py:14: accepting connection from ('192.168.1.31', 51631)
2023-06-12 14:58:20,922 INFO client.py:53: 
2023-06-12 14:58:20,937 INFO server.py:31: Connection lost
2023-06-12 14:58:22,014 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:22,014 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:22,015 INFO server.py:14: accepting connection from ('192.168.1.31', 51632)
2023-06-12 14:58:22,825 INFO client.py:53: 
2023-06-12 14:58:22,841 INFO server.py:31: Connection lost
2023-06-12 14:58:23,886 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:23,886 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:23,887 INFO server.py:14: accepting connection from ('192.168.1.31', 51633)
2023-06-12 14:58:26,239 INFO client.py:53: 
2023-06-12 14:58:26,254 INFO server.py:31: Connection lost
2023-06-12 14:58:27,438 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:27,438 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:27,440 INFO server.py:14: accepting connection from ('192.168.1.31', 51635)
2023-06-12 14:58:29,331 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:58:29,333 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:58:29,334 INFO server.py:14: accepting connection from ('192.168.1.31', 51636)
2023-06-12 14:59:23,038 INFO server.py:57: 
2023-06-12 14:59:23,054 INFO client.py:29: [Errno 54] Connection reset by peer
2023-06-12 14:59:23,054 INFO client.py:29: Connection lost
2023-06-12 14:59:25,031 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:59:25,035 INFO server.py:42: serving on ('0.0.0.0', 8888), ('::', 8888, 0, 0)
2023-06-12 14:59:27,175 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:59:27,176 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:59:27,177 INFO server.py:14: accepting connection from ('192.168.1.31', 51644)
2023-06-12 14:59:28,424 DEBUG selector_events.py:54: Using selector: KqueueSelector
2023-06-12 14:59:28,426 INFO client.py:38: connecting to 192.168.1.31:8888
2023-06-12 14:59:28,428 INFO server.py:14: accepting connection from ('192.168.1.31', 51645)
2023-06-12 14:59:32,266 INFO server.py:57: 
2023-06-12 14:59:32,283 INFO client.py:29: [Errno 54] Connection reset by peer
2023-06-12 14:59:32,283 INFO client.py:29: Connection lost
